export const mockCrmData = [
  {
    id: "1",
    industry: "Plumbing",
    businessName: "Victors Plumb.",
    email: "vicplumbingtz@example.com",
    dateReachedOut: "4/2/2025",
    callOverview: "went decent, he seemed intrigued",
    dateFollowedUp: null,
    followUpOverview: null,
    result: null,
  },
  {
    id: "2",
    industry: "Handyman",
    businessName: "AM Handyman",
    email: "am.handyman@example.com",
    dateReachedOut: "4/2/2025",
    callOverview: "left a message",
    dateFollowedUp: null,
    followUpOverview: null,
    result: null,
  },
  {
    id: "3",
    industry: "Handyman",
    businessName: "Miguel Handyman",
    email: "miguel@example.com",
    dateReachedOut: "4/2/2025",
    callOverview: "left a message",
    dateFollowedUp: null,
    followUpOverview: null,
    result: null,
  },
  {
    id: "4",
    industry: "Cleaning",
    businessName: "Splendor furnish.",
    email: "splendor@example.com",
    dateReachedOut: "4/2/2025",
    callOverview: "left a message",
    dateFollowedUp: null,
    followUpOverview: null,
    result: null,
  },
  {
    id: "5",
    industry: "Plumbing",
    businessName: "ABC Plumbing",
    email: "abc@example.com",
    dateReachedOut: "4/1/2025",
    callOverview: "Interested in services",
    dateFollowedUp: "4/3/2025",
    followUpOverview: "Scheduled a demo",
    result: "Converted to Client",
  },
  {
    id: "6",
    industry: "Cleaning",
    businessName: "Sparkle Clean",
    email: "sparkle@example.com",
    dateReachedOut: "4/1/2025",
    callOverview: "Spoke with manager",
    dateFollowedUp: "4/3/2025",
    followUpOverview: "Not interested at this time",
    result: "Rejected - Price",
  },
  {
    id: "7",
    industry: "Handyman",
    businessName: "Fix-It-All",
    email: "fixit@example.com",
    dateReachedOut: "4/1/2025",
    callOverview: "Very interested",
    dateFollowedUp: "4/3/2025",
    followUpOverview: "Requested proposal",
    result: "Converted to Client",
  },
  {
    id: "8",
    industry: "Plumbing",
    businessName: "Quick Plumbers",
    email: "quick@example.com",
    dateReachedOut: "3/30/2025",
    callOverview: "Spoke with owner",
    dateFollowedUp: "4/1/2025",
    followUpOverview: "Interested but busy",
    result: null,
  },
]

